spring:
    datasource:
        driverClassName: org.h2.Driver
        username: sa
        password:
        url: jdbc:h2:mem:testdb
    h2:
        console:
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
forum:
    jwt:
        expiration: 86400000
        secret: 'secret'